eCommerceSite/Controllers/CartController.cs
using eCommerceSite.Data;
using eCommerceSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace eCommerceSite.Controllers
{
    public class CartController : Controller
    {
        private readonly ProductContext _context;
        private readonly IHttpContextAccessor _httpContext;
        public CartController(ProductContext context, IHttpContextAccessor httpContext)
        {
            _context = context;
            _httpContext = httpContext;
        }
        /// <summary>
        /// Adds a product to the shopping cart
        /// </summary>
        /// <param name="id">The id of the product to add</param>
        /// <returns></returns>
        public async Task<IActionResult> Add(int id, string prevUrl)
        {
            // Get the product from the database
            Product p = await ProductDB.getProductAsync(_context, id);

            CookieHelper.addProductToCart(_httpContext, p);

            TempData["Message"] = $"{p.Title} added successfully";

            // Redirect back to previous page
            return Redirect(prevUrl);
        }

        public IActionResult Summary()
        {
            return View(CookieHelper.getCartProducts(_httpContext));
        }
    }
}

eCommerceSite/Controllers/ProductController.cs
using eCommerceSite.Data;
using eCommerceSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eCommerceSite.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductContext _context;
        public ProductController(ProductContext context)
        {
            _context = context;

        }

        /// <summary>
        /// Displays a view that lists a page products.
        /// </summary>
        public async Task<IActionResult> Index(int? id)
        {
            int pageNum = id ?? 1;
            const int pageSize = 3;
            ViewData["CurrentPage"] = pageNum;

            int numProducts = await ProductDB.getTotalProductsAsync(_context);
            int totalPages = (int)Math.Ceiling((double)numProducts / pageSize);
            ViewData["MaxPage"] = totalPages;
            List<Product> products = await ProductDB.getAllProductsAsync(_context, pageSize, pageNum);



            //Send list of products to view to be displayed
            return View(products);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Product p)
        {
            if (ModelState.IsValid)
            {
                await ProductDB.addProductAsync(_context, p);

                TempData["Message"] = $"{p.Title} was added successfully!";

                //redirect back to catalog page.
                return RedirectToAction("Index");
            }
            return View();
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            //Query syntax.
            Product p = await ProductDB.getProductAsync(_context, id);
            //Method syntax
            //Product p2 = await _context.Products.Where(prod => prod.ProductId == id).SingleAsync();
            return View(p);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Product p)
        {
            if(ModelState.IsValid)
            {
                _context.Entry(p).State = EntityState.Modified;
                await _context.SaveChangesAsync();

                ViewData["Message"] = $"{p.Title} updated successfully";
            }
            return View(p);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Product p = await ProductDB.getProductAsync(_context,id);
            return View(p);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Product p = await ProductDB.getProductAsync(_context, id);
            _context.Entry(p).State = EntityState.Deleted;
            await _context.SaveChangesAsync();

            TempData["Message"] = $"{p.Title} was deleted successfully!";

            return RedirectToAction("Index");
        }
    }
}

eCommerceSite/Controllers/UserController.cs
using eCommerceSite.Data;
using eCommerceSite.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eCommerceSite.Controllers
{
    public class UserController : Controller
    {
        private readonly ProductContext _context;

        public UserController(ProductContext context)
        {
            _context = context;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel reg)
        {
            if(ModelState.IsValid)
            {
                //Check if username/email is in use
                bool isEmailTaken = await (from account in _context.UserAccounts
                                    where account.Email == reg.Email
                                    select account).AnyAsync();

                //if so, add custom error message and send back to view
                if(isEmailTaken)
                {
                    ModelState.AddModelError(nameof(RegisterViewModel.Email), "Email is already in use");
                }

                bool isUserNameTaken = await(from account in _context.UserAccounts
                                       where account.UserName == reg.Username
                                       select account).AnyAsync();
                if(isUserNameTaken)
                {
                    ModelState.AddModelError(nameof(RegisterViewModel.Username), "Username is already in use");
                }

                if(isEmailTaken || isUserNameTaken)
                {
                    return View(reg);
                }


                //Map data to user account instance/object
                UserAccount acc = new UserAccount()
                {
                    DateOfBirth = reg.DateOfBirth,
                    Email = reg.Email,
                    Password = reg.Password,
                    UserName = reg.Username
                };
                //add to DB
                _context.UserAccounts.Add(acc);
                await _context.SaveChangesAsync();

                logUserIn(acc.UserId);

                //redirect to home page
                return RedirectToAction("Index", "Home");
            }
            return View(reg);
        }

        public IActionResult Login()
        {
            //Check if user is already logged into website
            if(HttpContext.Session.GetInt32("UserId").HasValue)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel log)
        {
            if (!ModelState.IsValid)
            {
                return View(log);
            }
            UserAccount acc =
                await (from u in _context.UserAccounts
                       where (u.UserName == log.UsernameOrEmail || u.Email == log.UsernameOrEmail) && u.Password == log.Password
                       select u).SingleOrDefaultAsync();
            /* 
            Another way of doing it in method syntax
            UserAccount account = 
                _context.UserAccounts.Where(userAcc => userAcc.UserName == log.userNameOrEmail || userAcc.email == log.userNameOrEmail && userAcc.Password == log.Password).SingleOrDefaultAsync();
            */
            if (acc == null)
            {
                //Custom error message
                ModelState.AddModelError(string.Empty, "Credentials were not found");
                return View(log);
            }
            logUserIn(acc.UserId);

            return RedirectToAction("Index", "Home");
        }

        private void logUserIn(int accountId)
        {
            //Log user into website
            HttpContext.Session.SetInt32("UserId", accountId);
        }

        public IActionResult Logout()
        {
            //Removes all current session data.
            HttpContext.Session.Clear();
            return RedirectToAction(actionName:"Index", controllerName:"Home");
        }
    }
}

eCommerceSite/Views/Shared/_Layout.cshtml
@using Microsoft.EntityFrameworkCore
@inject IHttpContextAccessor sessionData
@inject ProductContext db
@{
    int? userId = sessionData.HttpContext.Session.GetInt32("UserId");
    string userName = null;
    if (userId.HasValue)
    {
        string userNameFromSession = sessionData.HttpContext.Session.GetString("Username");
        if (userNameFromSession == null)
        {
            userName = await (from u in db.UserAccounts
                              where u.UserId == userId
                              select u.UserName).SingleOrDefaultAsync();
            sessionData.HttpContext.Session.SetString("Username", userName);
        }
        else
        {
            userName = userNameFromSession;
        }
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eCommerceSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eCommerceSite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <span class="badge badge-pill badge-secondary"><a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a></span>
                        </li>
                        <li class="nav-item">
                            <span class="badge badge-pill badge-secondary"> <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a></span>
                        </li>
                        <li class="nav-item">
                            <span class="badge badge-pill badge-primary"><a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Product Catalog</a></span>
                        </li>
                        @if (userId == null) //If the user is not logged in
                        {
                            <li class="nav-item">
                                <span class="badge badge-pill badge-success"><a class="nav-link text-dark" asp-controller="User" asp-action="Register">Register an Account</a></span>
                            </li>
                            <li class="nav-item">
                                <span class="badge badge-pill badge-success"><a class="nav-link text-dark" asp-controller="User" asp-action="Login">Login</a></span>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item"><a class="nav-link text-dark ">Welcome @userName!</a></li>
                            <li class="nav-item"><a class="nav-link text-dark" asp-controller="User" asp-action="Logout">Logout</a></li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cart" asp-action="Summary">
                                @{
                                    int total = @CookieHelper.getTotalCartProducts(sessionData);
                                }
                                @if (total == 0)
                                {
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-minecart" viewBox="0 0 16 16">
                                        <path d="M4 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8-1a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM.115 3.18A.5.5 0 0 1 .5 3h15a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 14 12H2a.5.5 0 0 1-.491-.408l-1.5-8a.5.5 0 0 1 .106-.411zm.987.82 1.313 7h11.17l1.313-7H1.102z" />
                                    </svg>
                                }
                                else
                                {
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-minecart-loaded" viewBox="0 0 16 16">
                                        <path d="M4 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8-1a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM.115 3.18A.5.5 0 0 1 .5 3h15a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 14 12H2a.5.5 0 0 1-.491-.408l-1.5-8a.5.5 0 0 1 .106-.411zm.987.82 1.313 7h11.17l1.313-7H1.102z" />
                                        <path fill-rule="evenodd" d="M6 1a2.498 2.498 0 0 1 4 0c.818 0 1.545.394 2 1 .67 0 1.552.57 2 1h-2c-.314 0-.611-.15-.8-.4-.274-.365-.71-.6-1.2-.6-.314 0-.611-.15-.8-.4a1.497 1.497 0 0 0-2.4 0c-.189.25-.486.4-.8.4-.507 0-.955.251-1.228.638-.09.13-.194.25-.308.362H3c.13-.147.401-.432.562-.545a1.63 1.63 0 0 0 .393-.393A2.498 2.498 0 0 1 6 1z" />
                                    </svg>
                                    @total
                                }
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - eCommerceSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>